# Generated by Django 6.0.4 on 2026-05-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userType',
            new_name='user_type',
        ),
    ]
