# Generated by Django 6.0.4 on 2026-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_ride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.IntegerField(),
        ),
    ]
